apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cat-app
  template:
    metadata:
      labels:
        app: cat-app
    spec:
      containers:
        - name: cat-app-container
          image: janesee3/cat-application:1
          ports:
            - containerPort: 8080
